### ISSUE TITLE
interface 0 claimed by usbfs while 'python3' sets config #1

### ISSUE THREAD

**Issue by fermuch** [rsm-gh/akbl#61] opened 2019-05-29 13:04 UTC
# System information

+ Distribution name: `Ubuntu`
+ Distribution version: `19.04`
+ Python3 version: `Python 3.7.3`
+ akbl version: `2019.05.26`
+ Computer model: `Alienware 17 R5`
+ Daemon status: `True`

# Bug description

The daemon of akbl starts and seems to work, but when I issue any command from the GUI or the TUI, I get the following (infinite) lines on dmesg:

```
[1205715.557252] usb 1-4: usbfs: interface 0 claimed by usbfs while 'python3' sets config #1
[1205715.558377] usb 1-4: usbfs: process 21883 (python3) did not claim interface 0 before use
[1205715.559109] usb 1-4: usbfs: interface 0 claimed by usbfs while 'python3' sets config #1
[1205715.560457] usb 1-4: usbfs: process 21883 (python3) did not claim interface 0 before use
[1205715.561230] usb 1-4: usbfs: interface 0 claimed by usbfs while 'python3' sets config #1
[1205715.562408] usb 1-4: usbfs: process 21883 (python3) did not claim interface 0 before use
[1205715.563346] usb 1-4: usbfs: interface 0 claimed by usbfs while 'python3' sets config #1
[1205715.564738] usb 1-4: usbfs: process 21883 (python3) did not claim interface 0 before use
[1205715.565656] usb 1-4: usbfs: interface 0 claimed by usbfs while 'python3' sets config #1
[1205715.566967] usb 1-4: usbfs: process 21883 (python3) did not claim interface 0 before use
[1205715.567701] usb 1-4: usbfs: interface 0 claimed by usbfs while 'python3' sets config #1
[1205715.568815] usb 1-4: usbfs: process 21883 (python3) did not claim interface 0 before use
[1205715.569777] usb 1-4: usbfs: interface 0 claimed by usbfs while 'python3' sets config #1
[1205715.570914] usb 1-4: usbfs: process 21883 (python3) did not claim interface 0 before use
[1205715.571591] usb 1-4: usbfs: interface 0 claimed by usbfs while 'python3' sets config #1
[1205715.572736] usb 1-4: usbfs: process 21883 (python3) did not claim interface 0 before use
[1205715.573610] usb 1-4: usbfs: interface 0 claimed by usbfs while 'python3' sets config #1
[1205715.574720] usb 1-4: usbfs: process 21883 (python3) did not claim interface 0 before use
[1205715.575589] usb 1-4: usbfs: interface 0 claimed by usbfs while 'python3' sets config #1
[1205715.576836] usb 1-4: usbfs: process 21883 (python3) did not claim interface 0 before use
[1205715.577660] usb 1-4: usbfs: interface 0 claimed by usbfs while 'python3' sets config #1
[1205715.578863] usb 1-4: usbfs: process 21883 (python3) did not claim interface 0 before use
[1205715.579622] usb 1-4: usbfs: interface 0 claimed by usbfs while 'python3' sets config #1
[1205715.580784] usb 1-4: usbfs: process 21883 (python3) did not claim interface 0 before use
```

It never stops. The only way to stop it is to restart the daemon.

**Comment by rsm-gh** [comment] 2019-06-04 07:50
Hi @fermuch,

I'll try to reproduce the bug by testing the software under Ubuntu, I currently have no problem with ArchLinux.

**Comment by fermuch** [comment] 2019-06-08 17:04
Thanks!

If there is a way for me to help you, please tell me!

**Comment by tuxkernel** [comment] 2019-06-12 16:19
+1

**Comment by rsm-gh** [comment] 2019-06-16 13:31
Hello guys, 

I was making the tests and everything is working alright but I just realized that I'm using ubuntu 18.04.2 LTS. I'll check with the newest update.

![Screenshot from 2019-06-16 13-25-58](https://user-images.githubusercontent.com/11134652/59564777-6e078400-903a-11e9-8dfa-27e9d05f9ac2.png)

~rsm

**Comment by tuxkernel** [comment] 2019-06-17 06:12
Hi guys:

I've been reading a little out there. It seems there are any conflict between usbhid, usbfs and python3 (claiming interface), because usbhid and usbfs were not compiled like kernel modules. If a run `sudo dmesg`, I get the following related to akbl:

systemd[1]: Configuration file /usr/lib/systemd/system/akbl.service is marked executable. Please remove executable permission bits. Proceeding anyway.

usb 2-1.4: config 1 interface 0 altsetting 0 has 2 endpoint descriptors, different from the interface descriptor's value: 1

usb 2-1.4: usbfs: interface 0 claimed by usbhid while 'python3' sets config #1

I tried hide these messages, writing a quirk in `etc/modprobe.d/` and `etc/default/grub` (kernel boot parameters) with no success. I've been reading threads and there are a million issues related with usbhid, usbfs and python. After all, I think, these annoying messages are just "warnings" because akbl is working well.

@rsm-gh I consider close this issue. What do you think?

Regards

Tuxkernel...

**Comment by rsm-gh** [comment] 2019-06-21 10:15
Hi @tuxkernel,

I ignored that akbl was working well and those were just warning messages. Anyways it is good to know it and thanks for your researches.

Beside the problems you have, I noticed the warning concerning the executable permission on ` /usr/lib/systemd/system/akbl.service`. I'll take a look to that.

Also, since I tested under Ubuntu 18, and you're confirming the use under Ubuntu 19, I'll close [this thread](https://github.com/rsm-gh/akbl/issues/15).

Regards,
rsm

**Closed** 2019-06-21 10:16 UTC
Labels: bug, help wanted

**Comment by tuxkernel** [comment] 2019-06-22 06:40
Hi @rsm-gh 

Related to akbl.service. I fixed creating a new akbl.service (read only) in `/etc/systemd/system/`

Look:

![akbl](https://user-images.githubusercontent.com/785911/59960460-12038c00-948e-11e9-92a5-3587f504267e.png)

It was only chmod -x permission. No more annoying dmesg message! ;-)´

**Comment by rsm-gh** [comment] 2019-06-22 09:56
Hi @tuxkernel ,

I just [made the modifications ](https://github.com/rsm-gh/akbl/commit/597d5c2cebdb210574535ec9491f3e45967fdc89). Thanks for pointing this,

~rsm
