### ISSUE TITLE
Add support to Alienware 17 R5

### ISSUE THREAD

**Issue by BrunoSDomingues** [rsm-gh/akbl#57] opened 2019-04-11 20:22 UTC
# System information

+ Distribution name: Linux Mint - Cinnamon Edition
+ Distribution version: 19.1
+ Python3 version: 3.6.7
+ akbl version: 2019.01.13
+ Computer model: Alienware 17 R5
+ Daemon status: True

# Bug description
On this [file](https://github.com/rsm-gh/akbl/files/3070425/lsusb17r5output.txt) is the output of running the lsusb -D command, and when I run the block testing I get the following [error](https://user-images.githubusercontent.com/38738937/55990532-3c5eef00-5c7e-11e9-8ef4-0918599c36b9.png).

**Comment by rsm-gh** [comment] 2019-04-12 21:20
Hello,

I just committed the fixes to the block testing window and added the configuration file for your computer! Probably you will now be able to launch the GUI :)

Keep me updated if you have problems or if you succeed to configure the computer,
-rsm

**Comment by BrunoSDomingues** [comment] 2019-04-14 02:30
Hello again,

The good news is that I can launch the GUI and it detects correctly the current light theme. The bad is that I tried to turn the lights off to test it and I got ![this output](https://user-images.githubusercontent.com/38738937/56087563-108d6600-5e44-11e9-80ac-16fb6fbd0471.png).

Thanks for taking your time out to help me!

**Comment by rsm-gh** [comment] 2019-04-14 08:49
Dam, the problem that you are having is known and I cant fix it since I can not reproduce it. To know more about it you need to use the block testing window. 

Here is the full detail: [unsupported serialized class: usb.core.USBError #40](https://github.com/rsm-gh/akbl/issues/40)

**Comment by rsm-gh** [comment] 2024-06-22 09:38
Duplicated of https://github.com/rsm-gh/akbl/issues/47

**Closed by rsm-gh** 2024-06-22 09:38 UTC
Labels: enhancement
