### ISSUE TITLE
Does it support Alienware 17 R3?

### ISSUE THREAD

**Issue by michaldybczak** [rsm-gh/akbl#43] opened 2018-08-10 05:18 UTC
# System information

+ Distribution name: Manjaro KDE 64bit
+ Distribution version: rolling-release, unstable branch so packages are the same as on Arch stable
+ Python version: 3.7.0-3
+ Computer model: Alienware 17 R3
+ Output of the command `alienware-kbl --daemon-is-on`:

Haven't installed it yet and I hoped to get info first since there is no clean install way on Arch based systems (no AUR package). Pip install is kinda risky and sometimes problematic on Arch. It's nice to have it but any package outside pacman database usually can run into issues with time.

Also, there is no gksu (probably replaced with gksu-polkit?) package anymore so I assume the Arch install info on the site is outdated and that also raises questions.

# Bug description

**Comment by rsm-gh** [comment] 2018-08-12 07:57
Hi @michaldybczak, I'm currently in holidays without my PC, I'll give you the the anwser in one or two weeks. 

Regards

**Comment by michaldybczak** [comment] 2018-08-12 09:31
No problem. I've been living without keyboard light support on Linux since over 2 years so I can wait a bit longer.

**Comment by rsm-gh** [comment] 2018-08-21 15:29
@michaldybczak  so! I have your answers and since the Issue is not related in to a bug I'll close it ! Anyways if you have a problem during the installation feel you free of opening a bug report for the Alienware 17 R13.

1) There's no clean install in arch. No, I do not provide or build any Debian / AUR package because it demands a lot effort to be maintained. Along time ago I used to do it and it was a lot of pain.

Instead, I created a "setup" script that works on most of Linux distributions. I personally use Arch and I know that many users use Ubuntu. Beside that I also try to maintain the software for Debian since I don't like Ubuntu.

Anyways you can be sure that if you are using the same packages than Arch, the software will always work. I do not risk of changing my main distro since I love Arch. 

For updating the software, you can even do it in a single command line `git clone https://github.com/rsm-gh/akbl.git &&  cd akbl && ./setup && cd ../ && rm -rf akbl`, or creating a more complicated script, but at least I will not create an AUR package.

2) `gksu` is not anymore necessary ! I forgot to remove it from the website.

3) The use of `pip install serpent` is not necessary anymore since at least for Arch, there seems to be an official package `python-serpent`.

4) Yep, the Alienware 17X R3 is supported. Its configuration file exists and it is listed as [Eveything works good](https://rsm-gh.github.io/software/akbl/support/). If you have any problem don't hesitate to open a bug report / or if it works, it would be nice to have a feedback.

I'll update the installation info of the website.

Kind regards,
rsm

**Closed by rsm-gh** 2018-08-21 15:29 UTC

**Comment by michaldybczak** [comment] 2018-08-22 19:01
Thanks! Will try it then when I find some time.

I'm curious if it supports that colorful mode that I use ;P. I guess I will find out.
